import { initializeApp } from "https://www.gstatic.com/firebasejs/11.7.1/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, sendEmailVerification, sendPasswordResetEmail, onAuthStateChanged, reload, signInWithEmailAndPassword, signOut, updateProfile } from "https://www.gstatic.com/firebasejs/11.7.1/firebase-auth.js";

const firebaseConfig = { apiKey:"AIzaSyDTVPpSaNp65ZWCwhP0YnztlUEhjkelhsM", authDomain:"billionaire-academy.firebaseapp.com", projectId:"billionaire-academy", storageBucket:"billionaire-academy.firebasestorage.app", messagingSenderId:"509691374429", appId:"1:509691374429:web:e95277af1e31f0302096b4", measurementId:"G-TH4VQ95H06" };
const auth = getAuth(initializeApp(firebaseConfig));
auth.useDeviceLanguage();
const pages=document.querySelectorAll(".page"),navLinks=document.querySelectorAll("nav a"),modal=document.getElementById("auth-modal"),views=document.querySelectorAll(".auth-view"),loginForm=document.getElementById("login-form"),signupForm=document.getElementById("signup-form"),navActions=document.querySelector(".nav-actions");
function showPage(id){pages.forEach(p=>p.classList.toggle("active",p.id===id));navLinks.forEach(a=>a.classList.toggle("active",a.getAttribute("href")===`#${id}`));window.scrollTo({top:0,behavior:"smooth"});}
function setView(name){views.forEach(v=>v.classList.add("hidden"));document.querySelector(`.${name}-view`).classList.remove("hidden");setMessage("");}
function setMessage(message,type="error"){let el=document.querySelector(".auth-message");if(!el){el=document.createElement("p");el.className="auth-message";document.querySelector(".modal-box").append(el);}el.textContent=message;el.dataset.type=type;}
function errorText(e){return ({"auth/email-already-in-use":"An account already exists with this email. Please log in.","auth/invalid-credential":"Incorrect email or password.","auth/invalid-email":"Please enter a valid email address.","auth/weak-password":"Use a password with at least 6 characters.","auth/too-many-requests":"Too many attempts. Please wait and try again.","auth/network-request-failed":"Network issue. Check your connection and try again."})[e.code]||"Something went wrong. Please try again.";}
function openAuth(mode){modal.classList.add("show");modal.setAttribute("aria-hidden","false");setView(mode);}function closeAuth(){modal.classList.remove("show");modal.setAttribute("aria-hidden","true");}function showVerification(email){document.getElementById("verify-email").textContent=email;setView("verify");}
function renderUser(user){if(!user){navActions.innerHTML='<button class="login-open ghost">Log in</button><button class="signup-open button small">Start learning <b>&nearr;</b></button>';navActions.querySelector(".login-open").onclick=()=>openAuth("login");navActions.querySelector(".signup-open").onclick=()=>openAuth("signup");return;}const name=(user.displayName||user.email.split("@")[0]).split(" ")[0];navActions.innerHTML=`<span class="user-chip" title="${user.email}"><i>${name.charAt(0).toUpperCase()}</i>${name}</span><button class="signout ghost">Log out</button>`;navActions.querySelector(".signout").onclick=()=>signOut(auth);}
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener("click",e=>{const id=link.getAttribute("href").slice(1);if(document.getElementById(id)){e.preventDefault();showPage(id);}}));document.querySelectorAll(".login-open").forEach(b=>b.onclick=()=>openAuth("login"));document.querySelectorAll(".signup-open").forEach(b=>b.onclick=()=>openAuth("signup"));document.querySelector(".close").onclick=closeAuth;modal.onclick=e=>{if(e.target===modal)closeAuth();};document.querySelector(".switch-signup").onclick=()=>setView("signup");document.querySelector(".switch-login").onclick=()=>setView("login");
document.querySelector('.form-row a').onclick=async e=>{e.preventDefault();const email=loginForm.querySelector('[type="email"]').value.trim();if(!email)return setMessage("Enter your email address first, then select Forgot password.");try{await sendPasswordResetEmail(auth,email);setMessage("Password-reset instructions have been sent. Check your inbox.","success");}catch(error){setMessage(errorText(error));}};
signupForm.onsubmit=async e=>{e.preventDefault();const name=signupForm.querySelector('[type="text"]').value.trim(),email=signupForm.querySelector('[type="email"]').value.trim(),password=signupForm.querySelector('[type="password"]').value,submit=signupForm.querySelector('button[type="submit"]');submit.disabled=true;submit.textContent="Creating account...";try{const c=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(c.user,{displayName:name});await sendEmailVerification(c.user);showVerification(email);}catch(error){setMessage(errorText(error));}finally{submit.disabled=false;submit.innerHTML="Create account <b>&rarr;</b>";}};
loginForm.onsubmit=async e=>{e.preventDefault();const email=loginForm.querySelector('[type="email"]').value.trim(),password=loginForm.querySelector('[type="password"]').value,submit=loginForm.querySelector('button[type="submit"]');submit.disabled=true;submit.textContent="Logging in...";try{const c=await signInWithEmailAndPassword(auth,email,password);await reload(c.user);if(!auth.currentUser.emailVerified){showVerification(auth.currentUser.email);return;}closeAuth();showPage("academy");}catch(error){setMessage(errorText(error));}finally{submit.disabled=false;submit.innerHTML="Log in <b>&rarr;</b>";}};
document.querySelector(".resend").onclick=async()=>{try{if(!auth.currentUser)throw new Error();await sendEmailVerification(auth.currentUser);setMessage("A new verification email has been sent.","success");}catch{setMessage("Please log in again before requesting a new verification email.");}};onAuthStateChanged(auth,renderUser);
